export const EBusinessType = {
  SOFTWARE: "software_development",
  WEB_DEVELOPMENT: "web_development",
  MOBILE_APP_DEV: "mobile_app_development",
  CLOUD_SERVICES: "cloud_services",
  ARTIFICIAL_INTELLIGENCE: "artificial_intelligence",
  CYBERSECURITY: "cybersecurity",
  BIG_DATA_ANALYTICS: "big_data_analytics",
  BLOCKCHAIN: "blockchain_technology",
  IT_CONSULTING: "it_consulting",
  NETWORKING: "networking",
  IOT: "internet_of_things",
  VIRTUAL_REALITY: "virtual_reality",
  AUGMENTED_REALITY: "augmented_reality",
  E_COMMERCE_SOLUTIONS: "e_commerce_solutions",
  DIGITAL_PAYMENT_SYSTEMS: "digital_payment_systems",
  WEB_ANALYTICS: "web_analytics",
  SEARCH_ENGINE_OPTIMIZATION: "search_engine_optimization",
  SOCIAL_MEDIA_MARKETING: "social_media_marketing",
  UI_UX_DESIGN: "ui_ux_design",
  GAME_DEVELOPMENT: "game_development",
  OTHERS: 'others'
}
